### ISSUE TITLE
[Bug] Pre built binary fails to install on MacOs

### ISSUE THREAD

**Issue by BlueFalconHD** [X1nto/VencordInstaller#2]
Commands run:
```bash
npm i -g pnpm                                              
git clone https://github.com/Vendicated/Vencord
cd Vencord
pnpm i
pnpm build

# downloaded and moved to Vencord directory

chmod +x ./vencord_installer && sudo ./vencord_installer
```

<details>
	<summary>OS Info</summary>
	<pre><code>  System Version:	macOS 12.3 (21E230)
  Kernel Version:	Darwin 21.4.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal</code></pre>
</details>

<details>
	<summary>File Tree</summary>
	<pre><code>.
├── CONTRIBUTING.md
├── LICENSE
├── README.md
├── browser
│   ├── Vencord.ts
│   ├── VencordNativeStub.ts
│   ├── background.js
│   ├── content.js
│   └── manifest.json
├── build.mjs
├── buildWeb.mjs
├── dist
│   ├── patcher.js
│   ├── patcher.js.map
│   ├── preload.js
│   ├── preload.js.map
│   └── renderer.js
├── install.ps1
├── install.sh
├── node_modules
│   ├── @types
│   │   ├── node -> ../.pnpm/@types+node@18.7.13/node_modules/@types/node
│   │   ├── react -> ../.pnpm/@types+react@18.0.17/node_modules/@types/react
│   │   └── yazl -> ../.pnpm/@types+yazl@2.4.2/node_modules/@types/yazl
│   ├── discord-types -> .pnpm/discord-types@1.3.26/node_modules/discord-types
│   ├── electron -> .pnpm/electron@20.1.0/node_modules/electron
│   ├── electron-devtools-installer -> .pnpm/electron-devtools-installer@3.2.0/node_modules/electron-devtools-installer
│   ├── esbuild -> .pnpm/esbuild@0.15.5/node_modules/esbuild
│   └── yazl -> .pnpm/yazl@2.5.1/node_modules/yazl
├── package.json
├── pnpm-lock.yaml
├── src
│   ├── Vencord.ts
│   ├── VencordNative.ts
│   ├── api
│   │   ├── MessageEvents.ts
│   │   ├── Notices.ts
│   │   ├── index.ts
│   │   └── settings.ts
│   ├── components
│   │   ├── ErrorBoundary.tsx
│   │   ├── ErrorCard.tsx
│   │   ├── Flex.tsx
│   │   ├── Link.tsx
│   │   ├── Settings.tsx
│   │   ├── Updater.tsx
│   │   └── index.ts
│   ├── globals.d.ts
│   ├── ipcMain
│   │   ├── index.ts
│   │   └── updater.ts
│   ├── patcher.ts
│   ├── plugins
│   │   ├── STFU.ts
│   │   ├── apiMessageEvents.ts
│   │   ├── apiNotices.ts
│   │   ├── banger.ts
│   │   ├── betterGifAltText.ts
│   │   ├── betterUploadButton.ts
│   │   ├── clickableRoleDot.ts
│   │   ├── consoleShortcuts.ts
│   │   ├── experiments.ts
│   │   ├── iLoveSpam.ts
│   │   ├── ify.ts
│   │   ├── index.ts
│   │   ├── isStaff.ts
│   │   ├── messageActions.ts
│   │   ├── muteNewGuild.ts
│   │   ├── nitroBypass.ts
│   │   ├── noReplyMention.ts
│   │   ├── noSystemBadge.ts
│   │   ├── noTrack.ts
│   │   ├── plainFolderIcon.ts
│   │   ├── randomiseFileNames.ts
│   │   ├── settings.ts
│   │   ├── silentTyping.ts
│   │   ├── unindent.ts
│   │   └── viewIcons.tsx
│   ├── pluginsModule.d.ts
│   ├── preload.ts
│   ├── utils
│   │   ├── ChangeList.ts
│   │   ├── IpcEvents.ts
│   │   ├── constants.ts
│   │   ├── debounce.ts
│   │   ├── isWeb.ts
│   │   ├── logger.ts
│   │   ├── misc.tsx
│   │   ├── modal.tsx
│   │   ├── quickCss.ts
│   │   ├── types.ts
│   │   └── updater.ts
│   └── webpack
│       ├── common.tsx
│       ├── index.ts
│       ├── patchWebpack.ts
│       └── webpack.ts
├── tsconfig.json
├── uninstall.ps1
├── uninstall.sh
└── vencord_installer

19 directories, 82 files</code></pre>
</details>

**Comment by X1nto** [comment]
macOS is not supported at the moment

**Comment by BlueFalconHD** [comment]
> macOS is not supported at the moment

On Vendicated/Vencord it has macOS installation instructions which are the same as what I did. Is this just a miscommunication?

**Comment by X1nto** [comment]
> On Vendicated/Vencord it has macOS installation instructions which are the same as what I did. Is this just a miscommunication?

It is a miscommunication indeed, as this repo only states that it supports Windows and Linux. Although, macOS support is coming, I just need some help with it as I don't have a working mac with me.

**Comment by BlueFalconHD** [comment]
@X1nto if you need a macOS tester, I am your guy. I actually know how to debug and get you the info you need to fix problems.

**Comment by X1nto** [comment]
> @X1nto if you need a macOS tester, I am your guy. I actually know how to debug and get you the info you need to fix problems.

Thank you, I'll get in touch with you on Discord if you don't mind

**Comment by BlueFalconHD** [comment]
> > @X1nto if you need a macOS tester, I am your guy. I actually know how to debug and get you the info you need to fix problems.
> 
> Thank you, I'll get in touch with you on Discord if you don't mind

You can DM me at BlueFalconHD#0001
